import { auth, db } from './firebase.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, setPersistence, browserLocalPersistence, browserSessionPersistence, updateProfile, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { doc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const form = document.querySelector('form'); const message = document.getElementById('auth-message');
const showError = error => { const code = error?.code || ''; message.textContent = code.includes('invalid-credential') ? 'Incorrect email or password.' : code.includes('email-already-in-use') ? 'That email is already registered.' : code.includes('weak-password') ? 'Use a password with at least 6 characters.' : error?.message || 'Something went wrong. Please try again.'; };
onAuthStateChanged(auth, user => { if (user) location.replace('dashboard.html'); });
if (form?.id === 'login-form') { form.addEventListener('submit', async event => { event.preventDefault(); message.textContent=''; try { await setPersistence(auth, document.getElementById('remember').checked ? browserLocalPersistence : browserSessionPersistence); await signInWithEmailAndPassword(auth, document.getElementById('email').value.trim(), document.getElementById('password').value); } catch(error) { showError(error); } }); document.getElementById('forgot-password').addEventListener('click', async () => { const email=document.getElementById('email').value.trim(); if (!email) { message.textContent='Enter your email first, then try again.'; return; } try { await sendPasswordResetEmail(auth,email); message.style.color='#16835a'; message.textContent='Password reset email sent. Check your inbox.'; } catch(error) { showError(error); } }); }
if (form?.id === 'signup-form') { form.addEventListener('submit', async event => { event.preventDefault(); message.textContent=''; const name=document.getElementById('name').value.trim(), email=document.getElementById('email').value.trim(), password=document.getElementById('password').value; try { const result=await createUserWithEmailAndPassword(auth,email,password); await updateProfile(result.user,{displayName:name}); await setDoc(doc(db,'users',result.user.uid),{name,email,dailyGoal:8,weeklyGoal:40,monthlyGoal:160,theme:'light',createdAt:serverTimestamp()}); location.replace('dashboard.html'); } catch(error) { showError(error); } }); }
