import { requireUser, secondsToClock, secondsToHours, dayRange, dailyStats, sessionsForDay, todayKey, formatTime, escapeHtml, notify, saveProfile } from './utils.js';
import { loadTimer, startTimer, pauseTimer, resumeTimer, endTimer } from './timer.js';
import { db } from './firebase.js';
import { doc, setDoc, serverTimestamp, Timestamp, collection, getDocs, deleteDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

let uid, profile, reminders = [], chart, inactiveTimer, idlePrompted = false;
let currentStats = { laptopSeconds: 0, offlineSeconds: 0, totalSeconds: 0, sessionCount: 0 };
const quotes = ['Every focused hour brings your goal closer.','The time is moving—use this moment well.','Small, steady effort creates remarkable results.','Keep going. Your future self is counting on today.','Focus now, celebrate later. You can do this.','Preparation turns pressure into confidence.','Stay focused. You have got this.','Use today well. Tomorrow is getting closer.'];

function modal(html) { document.getElementById('modal-root').innerHTML = `<div class="modal-backdrop"><div class="modal">${html}</div></div>`; }
function closeModal() { document.getElementById('modal-root').innerHTML = ''; }
async function runAction(button, busyLabel, action) { const original = button.innerHTML; button.disabled = true; button.innerHTML = busyLabel; try { await action(); } finally { if (button.isConnected) { button.disabled = false; button.innerHTML = original; } } }
const makeId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;

function showTimer(timer) { const display = document.getElementById('timer-display'), task = document.getElementById('timer-task'), status = document.getElementById('timer-status'), start = document.getElementById('timer-start'), startBtn = document.getElementById('start-button'), pauseBtn = document.getElementById('pause-button'), endBtn = document.getElementById('end-button'); if (!timer) { display.textContent = '00:00:00'; task.textContent = 'No active session'; status.textContent = 'READY'; status.className = 'status idle'; start.textContent = 'Choose a task to begin'; startBtn.classList.remove('hidden'); pauseBtn.classList.add('hidden'); endBtn.classList.add('hidden'); return; } display.textContent = secondsToClock(timer.duration); task.textContent = timer.task; status.textContent = timer.runningSince ? 'IN PROGRESS' : 'PAUSED'; status.className = `status ${timer.runningSince ? 'running' : 'paused'}`; start.textContent = `Started ${new Date(timer.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`; startBtn.classList.add('hidden'); pauseBtn.classList.remove('hidden'); pauseBtn.innerHTML = timer.runningSince ? '<i class="fa-solid fa-pause"></i> Pause' : '<i class="fa-solid fa-play"></i> Resume'; endBtn.classList.remove('hidden'); }
function renderStats(stat) { currentStats = stat || currentStats; const total = currentStats.totalSeconds || 0, goal = (profile.dailyGoal || 8) * 3600, pct = Math.min(100, total / goal * 100); document.getElementById('laptop-hours').textContent = secondsToHours(currentStats.laptopSeconds); document.getElementById('offline-hours').textContent = secondsToHours(currentStats.offlineSeconds); document.getElementById('total-hours').textContent = secondsToHours(total); document.getElementById('session-count').textContent = currentStats.sessionCount || 0; document.getElementById('goal-summary').textContent = `${secondsToHours(total)} of ${profile.dailyGoal || 8}h`; document.getElementById('goal-progress').style.width = `${pct}%`; document.getElementById('goal-percent').textContent = `${Math.round(pct)}% complete`; document.getElementById('goal-remaining').textContent = total >= goal ? 'Goal achieved' : `${secondsToHours(goal - total)} remaining`; }
function renderSessions(items) { const target = document.getElementById('today-sessions'); target.innerHTML = items.length ? items.map(session => `<div class="session-item"><span class="session-icon"><i class="fa-solid ${session.remark ? 'fa-book-open' : 'fa-laptop'}"></i></span><div class="session-info"><strong>${escapeHtml(session.task || session.remark)}</strong><small>${formatTime(session.startTime)} – ${formatTime(session.endTime)}</small></div><span class="session-duration">${secondsToHours(session.durationSeconds)}</span></div>`).join('') : '<p class="empty">Your completed sessions will appear here.</p>'; }
function dateLabel(key) { return new Date(`${key}T12:00:00`).toLocaleDateString([], { weekday: 'short' }).slice(0, 2); }
function renderChart(keys, map) { chart?.destroy(); chart = new Chart(document.getElementById('week-chart'), { type: 'bar', data: { labels: keys.map(dateLabel), datasets: [{ data: keys.map(key => (map[key]?.totalSeconds || 0) / 3600), backgroundColor: '#7592ff', borderRadius: 5, borderSkipped: false }] }, options: { responsive: true, plugins: { legend: { display: false }, tooltip: { callbacks: { label: item => `${item.raw.toFixed(1)}h total` } } }, scales: { x: { grid: { display: false }, border: { display: false }, ticks: { font: { size: 10 } } }, y: { beginAtZero: true, grid: { color: '#eef0f4' }, border: { display: false }, ticks: { font: { size: 10 }, callback: value => `${value}h` } } } } }); }
function computeStreak(map, keys) { let current = 0, longest = 0, run = 0; [...keys].reverse().forEach(key => { if ((map[key]?.totalSeconds || 0) > 0) { run++; longest = Math.max(longest, run); } else run = 0; }); for (const key of [...keys].reverse()) { if ((map[key]?.totalSeconds || 0) > 0) current++; else break; } return { current, longest }; }
async function loadDashboard() { const keys = dayRange(7), stats = await dailyStats(uid, keys[0], keys.at(-1)), map = Object.fromEntries(stats.map(item => [item.date, item])); renderStats(map[todayKey()] || { laptopSeconds: 0, offlineSeconds: 0, totalSeconds: 0, sessionCount: 0 }); renderChart(keys, map); const sessions = await sessionsForDay(uid, todayKey()); renderSessions([...sessions.laptop, ...sessions.offline].sort((a, b) => new Date(b.startTime?.toDate?.() || b.startTime) - new Date(a.startTime?.toDate?.() || a.startTime))); const streak = computeStreak(map, keys); document.getElementById('current-streak').textContent = `${streak.current} day streak`; document.getElementById('longest-streak').textContent = streak.longest; }

function openStart() { modal(`<h2>What are you working on?</h2><p>A clear task makes your history useful later.</p><label>Task name<input id="task-name" autofocus placeholder="e.g. SQL, Python, System Design" maxlength="80"></label><div class="modal-actions"><button id="cancel-modal" class="button secondary">Cancel</button><button id="confirm-start" class="button primary">Start session</button></div>`); document.getElementById('cancel-modal').onclick = closeModal; document.getElementById('confirm-start').onclick = event => runAction(event.currentTarget, 'Starting…', async () => { const task = document.getElementById('task-name').value.trim(); if (!task) { notify('Please enter what you are studying.', true); return; } await startTimer(uid, task); closeModal(); notify('Laptop session started.'); }); document.getElementById('task-name').focus(); }
function openOffline() { const now = new Date(), time = now.toTimeString().slice(0, 5); modal(`<h2>Add offline study</h2><p>Use this for book study, revision, and other offline work.</p><label>Start time<input id="offline-start" type="time" value="${time}"></label><label>End time<input id="offline-end" type="time" value="${time}"></label><label>Remark<textarea id="offline-remark" placeholder="e.g. Revision from book" maxlength="160"></textarea></label><div class="modal-actions"><button id="cancel-modal" class="button secondary">Cancel</button><button id="save-offline" class="button primary">Add entry</button></div>`); document.getElementById('cancel-modal').onclick = closeModal; document.getElementById('save-offline').onclick = event => runAction(event.currentTarget, 'Saving…', saveOffline); }
async function saveOffline() { const start = document.getElementById('offline-start').value, end = document.getElementById('offline-end').value, remark = document.getElementById('offline-remark').value.trim(); if (!start || !end || !remark) { notify('Enter a start time, end time, and remark.', true); return; } const date = todayKey(), startAt = new Date(`${date}T${start}`), endAt = new Date(`${date}T${end}`); if (endAt <= startAt) { notify('End time must be after start time.', true); return; } const duration = Math.round((endAt - startAt) / 1000), id = makeId(); await setDoc(doc(db, 'users', uid, 'offlineSessions', id), { remark, startTime: Timestamp.fromDate(startAt), endTime: Timestamp.fromDate(endAt), durationSeconds: duration, date, createdAt: serverTimestamp() }); const { updateDailyStats } = await import('./utils.js'); await updateDailyStats(uid, date, 0, duration, 1); closeModal(); notify('Offline study added.'); await loadDashboard(); }
function openGoal() { modal(`<h2>Daily goal</h2><p>Choose an achievable number of study hours.</p><label>Hours per day<input id="goal-input" type="number" min="0.5" max="24" step="0.5" value="${profile.dailyGoal || 8}"></label><div class="modal-actions"><button id="cancel-modal" class="button secondary">Cancel</button><button id="save-goal" class="button primary">Save goal</button></div>`); document.getElementById('cancel-modal').onclick = closeModal; document.getElementById('save-goal').onclick = async () => { const goal = Number(document.getElementById('goal-input').value); if (!goal || goal > 24) { notify('Enter a goal between 0.5 and 24 hours.', true); return; } profile.dailyGoal = goal; await saveProfile(uid, { dailyGoal: goal }); closeModal(); renderStats(currentStats); notify('Daily goal updated.'); }; }

const localInputValue = value => { const date = new Date(value), pad = number => String(number).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; };
const sortedReminders = () => [...reminders].sort((a, b) => new Date(a.at) - new Date(b.at));
function reminderContent(reminder, now) { const target = new Date(reminder.at), remaining = target - now; if (remaining <= 0) return todayKey(target) === todayKey(now) ? ['It is today!', `Today is your ${reminder.title}. All the best—give it your best effort!`] : ['Event completed', `${reminder.title} has passed. You can edit it to set a new date.`]; const minutes = Math.floor(remaining / 60000), days = Math.floor(minutes / 1440), hours = Math.floor(minutes % 1440 / 60), mins = minutes % 60, day = Math.floor(new Date(`${todayKey(now)}T12:00:00`).getTime() / 86400000); return [`${days} Days : ${String(hours).padStart(2, '0')} Hours : ${String(mins).padStart(2, '0')} Minutes`, quotes[(day + reminder.id.length) % quotes.length]]; }
function renderReminders() { const list = document.getElementById('reminder-list'), now = new Date(), items = sortedReminders(); list.innerHTML = items.length ? items.map(reminder => { const [time, message] = reminderContent(reminder, now); return `<article class="reminder-item"><div class="reminder-heading"><div><strong>${escapeHtml(reminder.title)}</strong><small>${new Date(reminder.at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</small></div><div class="reminder-actions"><button class="icon-button edit-reminder" data-id="${reminder.id}" aria-label="Edit ${escapeHtml(reminder.title)}"><i class="fa-solid fa-pen"></i></button><button class="icon-button delete-reminder" data-id="${reminder.id}" aria-label="Delete ${escapeHtml(reminder.title)}"><i class="fa-solid fa-trash"></i></button></div></div><p class="reminder-time">${time}</p><p class="reminder-message">${escapeHtml(message)}</p></article>`; }).join('') : '<p class="empty">Add an exam, deadline, or special event to see its countdown here.</p>'; }
async function loadReminders() { const ref = collection(db, 'users', uid, 'reminders'); const legacy = profile.countdownEvent; if (legacy?.title && legacy?.at) { await setDoc(doc(db, 'users', uid, 'reminders', 'legacy-countdown'), { title: legacy.title, at: legacy.at, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }, { merge: true }); await saveProfile(uid, { countdownEvent: null }); profile.countdownEvent = null; } const snapshot = await getDocs(ref); reminders = snapshot.docs.map(item => ({ id: item.id, ...item.data() })); renderReminders(); }
function openReminder(id) { const reminder = reminders.find(item => item.id === id), editing = Boolean(reminder), value = reminder?.at ? localInputValue(reminder.at) : ''; modal(`<h2>${editing ? 'Edit reminder' : 'Add reminder'}</h2><p>Keep an important date in view.</p><label>Reminder name<input id="reminder-name" maxlength="80" value="${escapeHtml(reminder?.title || '')}" placeholder="e.g. Mathematics exam"></label><label>Date and time<input id="reminder-at" type="datetime-local" value="${value}"></label><div class="modal-actions"><button id="cancel-modal" class="button secondary">Cancel</button><button id="save-reminder" class="button primary">${editing ? 'Save changes' : 'Save reminder'}</button></div>`); document.getElementById('cancel-modal').onclick = closeModal; document.getElementById('save-reminder').onclick = event => runAction(event.currentTarget, 'Saving…', async () => { const title = document.getElementById('reminder-name').value.trim(), at = document.getElementById('reminder-at').value; if (!title || !at) { notify('Enter a reminder name and date/time.', true); return; } const next = { id: reminder?.id || makeId(), title, at: new Date(at).toISOString() }; await setDoc(doc(db, 'users', uid, 'reminders', next.id), { title: next.title, at: next.at, updatedAt: serverTimestamp(), ...(editing ? {} : { createdAt: serverTimestamp() }) }, { merge: true }); reminders = editing ? reminders.map(item => item.id === next.id ? { ...item, ...next } : item) : [...reminders, next]; closeModal(); renderReminders(); notify(editing ? 'Reminder updated.' : 'Reminder added.'); }); }
function confirmReminderDeletion(id) { const reminder = reminders.find(item => item.id === id); if (!reminder) return; modal(`<h2>Delete reminder?</h2><p>“${escapeHtml(reminder.title)}” will be permanently deleted. This cannot be undone.</p><div class="modal-actions"><button id="cancel-modal" class="button secondary">Cancel</button><button id="confirm-delete-reminder" class="button danger">Delete</button></div>`); document.getElementById('cancel-modal').onclick = closeModal; document.getElementById('confirm-delete-reminder').onclick = event => runAction(event.currentTarget, 'Deleting…', async () => { await deleteDoc(doc(db, 'users', uid, 'reminders', id)); reminders = reminders.filter(item => item.id !== id); closeModal(); renderReminders(); notify('Reminder permanently deleted.'); }); }

function armIdle() { const reset = () => { clearTimeout(inactiveTimer); idlePrompted = false; inactiveTimer = setTimeout(() => { if (document.querySelector('#timer-status')?.textContent === 'IN PROGRESS' && !idlePrompted) { idlePrompted = true; modal(`<h2>You seem inactive.</h2><p>Your laptop session is still running. Would you like to pause it?</p><div class="modal-actions"><button id="continue-timer" class="button secondary">Continue</button><button id="idle-pause" class="button primary">Pause timer</button></div>`); document.getElementById('continue-timer').onclick = () => { closeModal(); reset(); }; document.getElementById('idle-pause').onclick = async () => { await pauseTimer(); closeModal(); notify('Timer paused.'); }; } }, 300000); }; ['mousemove','keydown','mousedown','touchstart'].forEach(event => addEventListener(event, reset, { passive: true })); reset(); }

requireUser(async (user, loadedProfile) => { uid = user.uid; profile = loadedProfile; document.getElementById('user-name').textContent = (profile.name || 'there').split(' ')[0]; document.getElementById('today-label').textContent = new Date().toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' }).toUpperCase(); loadTimer(uid, showTimer); document.getElementById('start-button').onclick = openStart; document.getElementById('pause-button').onclick = async () => { try { if (document.getElementById('timer-status').textContent === 'IN PROGRESS') { await pauseTimer(); notify('Timer paused.'); } else { await resumeTimer(); notify('Timer resumed.'); } } catch (error) { notify(error.message, true); } }; document.getElementById('end-button').onclick = event => runAction(event.currentTarget, 'Saving…', async () => { try { const done = await endTimer(); if (done) { notify(`Session saved: ${secondsToHours(done.duration)}`); await loadDashboard(); } } catch (error) { notify(error.message, true); } }); document.getElementById('offline-button').onclick = openOffline; document.getElementById('edit-goal').onclick = openGoal; document.getElementById('add-reminder').onclick = () => openReminder(); document.getElementById('reminder-list').onclick = event => { const button = event.target.closest('button[data-id]'); if (!button) return; if (button.classList.contains('edit-reminder')) openReminder(button.dataset.id); else confirmReminderDeletion(button.dataset.id); }; await Promise.all([loadDashboard(), loadReminders()]); setInterval(renderReminders, 60000); armIdle(); });
