import { requireUser, secondsToClock, secondsToHours, dayRange, dailyStats, sessionsForDay, todayKey, formatTime, escapeHtml, notify, saveProfile } from './utils.js';
import { loadTimer, startTimer, pauseTimer, resumeTimer, endTimer } from './timer.js';
import { db } from './firebase.js';
import { doc, setDoc, serverTimestamp, Timestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

let uid, profile, currentStats={laptopSeconds:0,offlineSeconds:0,totalSeconds:0,sessionCount:0}, chart, inactiveTimer, idlePrompted=false;
function modal(html) { document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`; }
function closeModal(){document.getElementById('modal-root').innerHTML='';}
async function runAction(button, busyLabel, action){const original=button.innerHTML;button.disabled=true;button.innerHTML=busyLabel;try{await action();}finally{if(button.isConnected){button.disabled=false;button.innerHTML=original;}}}
function showTimer(state){const display=document.getElementById('timer-display'), task=document.getElementById('timer-task'), status=document.getElementById('timer-status'), start=document.getElementById('timer-start'), startBtn=document.getElementById('start-button'), pauseBtn=document.getElementById('pause-button'), endBtn=document.getElementById('end-button'); if(!state){display.textContent='00:00:00';task.textContent='No active session';status.textContent='READY';status.className='status idle';start.textContent='Choose a task to begin';startBtn.classList.remove('hidden');pauseBtn.classList.add('hidden');endBtn.classList.add('hidden');return;} display.textContent=secondsToClock(state.duration); task.textContent=state.task; status.textContent=state.runningSince?'IN PROGRESS':'PAUSED';status.className=`status ${state.runningSince?'running':'paused'}`;start.textContent=`Started ${new Date(state.startTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;startBtn.classList.add('hidden');pauseBtn.classList.remove('hidden');pauseBtn.innerHTML=state.runningSince?'<i class="fa-solid fa-pause"></i> Pause':'<i class="fa-solid fa-play"></i> Resume';endBtn.classList.remove('hidden');}
function renderStats(stat){currentStats=stat||currentStats; const total=currentStats.totalSeconds||0, goal=(profile.dailyGoal||8)*3600,pct=Math.min(100,total/goal*100); document.getElementById('laptop-hours').textContent=secondsToHours(currentStats.laptopSeconds);document.getElementById('offline-hours').textContent=secondsToHours(currentStats.offlineSeconds);document.getElementById('total-hours').textContent=secondsToHours(total);document.getElementById('session-count').textContent=currentStats.sessionCount||0;document.getElementById('goal-summary').textContent=`${secondsToHours(total)} of ${profile.dailyGoal||8}h`;document.getElementById('goal-progress').style.width=`${pct}%`;document.getElementById('goal-percent').textContent=`${Math.round(pct)}% complete`;document.getElementById('goal-remaining').textContent=total>=goal?'Goal achieved':`${secondsToHours(goal-total)} remaining`;}
async function loadDashboard(){const keys=dayRange(7), stats=await dailyStats(uid,keys[0],keys.at(-1));const map=Object.fromEntries(stats.map(s=>[s.date,s]));renderStats(map[todayKey()]||{laptopSeconds:0,offlineSeconds:0,totalSeconds:0,sessionCount:0});renderChart(keys,map);const sessions=await sessionsForDay(uid,todayKey());renderSessions([...sessions.laptop,...sessions.offline].sort((a,b)=>new Date(b.startTime?.toDate?.()||b.startTime)-new Date(a.startTime?.toDate?.()||a.startTime)));const streak=computeStreak(map,keys);document.getElementById('current-streak').textContent=`${streak.current} day streak`;document.getElementById('longest-streak').textContent=streak.longest;}
function computeStreak(map,keys){let current=0,longest=0,run=0;[...keys].reverse().forEach(k=>{if((map[k]?.totalSeconds||0)>0){run++;longest=Math.max(longest,run)}else run=0});for(const k of [...keys].reverse()){if((map[k]?.totalSeconds||0)>0)current++;else break}return{current,longest};}
function renderSessions(items){const target=document.getElementById('today-sessions');target.innerHTML=items.length?items.map(s=>`<div class="session-item"><span class="session-icon"><i class="fa-solid ${s.remark?'fa-book-open':'fa-laptop'}"></i></span><div class="session-info"><strong>${escapeHtml(s.task||s.remark)}</strong><small>${formatTime(s.startTime)} – ${formatTime(s.endTime)}</small></div><span class="session-duration">${secondsToHours(s.durationSeconds)}</span></div>`).join(''):'<p class="empty">Your completed sessions will appear here.</p>';}
function renderChart(keys,map){chart?.destroy();const ctx=document.getElementById('week-chart');chart=new Chart(ctx,{type:'bar',data:{labels:keys.map(k=>dateLabel(k)),datasets:[{data:keys.map(k=>(map[k]?.totalSeconds||0)/3600),backgroundColor:'#7592ff',borderRadius:5,borderSkipped:false}]},options:{responsive:true,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw.toFixed(1)}h total`}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{font:{size:10}}},y:{beginAtZero:true,grid:{color:'#eef0f4'},border:{display:false},ticks:{font:{size:10},callback:v=>`${v}h`}}}}});}
function dateLabel(k){return new Date(`${k}T12:00:00`).toLocaleDateString([],{weekday:'short'}).slice(0,2)}
function openStart(){modal(`<h2>What are you working on?</h2><p>A clear task makes your history useful later.</p><label>Task name<input id="task-name" autofocus placeholder="e.g. SQL, Python, System Design" maxlength="80"></label><div class="modal-actions"><button type="button" id="cancel-modal" class="button secondary">Cancel</button><button type="button" id="confirm-start" class="button primary">Start session</button></div>`);document.getElementById('cancel-modal').onclick=closeModal;document.getElementById('confirm-start').onclick=async event=>{const button=event.currentTarget,task=document.getElementById('task-name').value.trim();if(!task){notify('Please enter what you are studying.',true);return;}await runAction(button,'Starting…',async()=>{try{await startTimer(uid,task);closeModal();notify('Laptop session started.');}catch(e){notify(`Could not start timer: ${e.message}`,true)}})};document.getElementById('task-name').focus();}
function openOffline(){const now=new Date(), time=now.toTimeString().slice(0,5);modal(`<h2>Add offline study</h2><p>Use this for book study, revision, and other offline work.</p><label>Start time<input id="offline-start" type="time" value="${time}"></label><label>End time<input id="offline-end" type="time" value="${time}"></label><label>Remark<textarea id="offline-remark" placeholder="e.g. Revision from book" maxlength="160"></textarea></label><div class="modal-actions"><button type="button" id="cancel-modal" class="button secondary">Cancel</button><button type="button" id="save-offline" class="button primary">Add entry</button></div>`);document.getElementById('cancel-modal').onclick=closeModal;document.getElementById('save-offline').onclick=event=>runAction(event.currentTarget,'Saving…',saveOffline);}
async function saveOffline(){const start=document.getElementById('offline-start').value,end=document.getElementById('offline-end').value,remark=document.getElementById('offline-remark').value.trim();if(!start||!end||!remark){notify('Enter a start time, end time, and remark.',true);return;}const key=todayKey(), s=new Date(`${key}T${start}`),e=new Date(`${key}T${end}`);if(e<=s){notify('End time must be after start time.',true);return;}const duration=Math.round((e-s)/1000), id=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;try{await setDoc(doc(db,'users',uid,'offlineSessions',id),{remark,startTime:Timestamp.fromDate(s),endTime:Timestamp.fromDate(e),durationSeconds:duration,date:key,createdAt:serverTimestamp()});const {updateDailyStats}=await import('./utils.js');await updateDailyStats(uid,key,0,duration,1);closeModal();notify('Offline study added.');await loadDashboard();}catch(error){notify(`Could not add offline study: ${error.message}`,true)}}
function openGoal(){modal(`<h2>Daily goal</h2><p>Choose an achievable number of study hours.</p><label>Hours per day<input id="goal-input" type="number" min="0.5" max="24" step="0.5" value="${profile.dailyGoal||8}"></label><div class="modal-actions"><button id="cancel-modal" class="button secondary">Cancel</button><button id="save-goal" class="button primary">Save goal</button></div>`);document.getElementById('cancel-modal').onclick=closeModal;document.getElementById('save-goal').onclick=async()=>{const goal=Number(document.getElementById('goal-input').value);if(!goal||goal>24){notify('Enter a goal between 0.5 and 24 hours.',true);return;}profile.dailyGoal=goal;await saveProfile(uid,{dailyGoal:goal});closeModal();renderStats(currentStats);notify('Daily goal updated.');};}
function armIdle(){const reset=()=>{clearTimeout(inactiveTimer);idlePrompted=false;inactiveTimer=setTimeout(()=>{const state=document.querySelector('#timer-status')?.textContent;if(state==='IN PROGRESS'&&!idlePrompted){idlePrompted=true;modal(`<h2>You seem inactive.</h2><p>Your laptop session is still running. Would you like to pause it?</p><div class="modal-actions"><button id="continue-timer" class="button secondary">Continue</button><button id="idle-pause" class="button primary">Pause timer</button></div>`);document.getElementById('continue-timer').onclick=()=>{closeModal();reset();};document.getElementById('idle-pause').onclick=async()=>{await pauseTimer();closeModal();notify('Timer paused.');};}},300000)};['mousemove','keydown','mousedown','touchstart'].forEach(x=>addEventListener(x,reset,{passive:true}));reset();}
requireUser(async(user,p)=>{uid=user.uid;profile=p;document.getElementById('user-name').textContent=(p.name||'there').split(' ')[0];document.getElementById('today-label').textContent=new Date().toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'}).toUpperCase();loadTimer(uid,showTimer);document.getElementById('start-button').onclick=openStart;document.getElementById('pause-button').onclick=async()=>{try{const isRunning=document.getElementById('timer-status').textContent==='IN PROGRESS';if(isRunning){await pauseTimer();notify('Timer paused.')}else{await resumeTimer();notify('Timer resumed.')}}catch(e){notify(e.message,true)}};document.getElementById('end-button').onclick=async()=>{try{const done=await endTimer();notify(`Session saved: ${secondsToHours(done.duration)}`);await loadDashboard();}catch(e){notify(e.message,true)}};document.getElementById('offline-button').onclick=openOffline;document.getElementById('edit-goal').onclick=openGoal;await loadDashboard();armIdle();});
