import { requireUser, allSessions, secondsToHours, formatTime, formatDate, escapeHtml, notify } from './utils.js';
import { exportCsv, exportExcel, exportPdf } from './export.js';
import { db } from './firebase.js';
import { doc, writeBatch, increment, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
let uid, laptop=[], offline=[], range='today';
const withinRange=(item)=>{const now=new Date(),date=new Date(`${item.date}T12:00:00`);if(document.getElementById('history-from').value||document.getElementById('history-to').value){const from=document.getElementById('history-from').value,to=document.getElementById('history-to').value;return(!from||item.date>=from)&&(!to||item.date<=to)}if(range==='all')return true;const days=range==='today'?0:range==='week'?6:29;now.setHours(0,0,0,0);const min=new Date(now);min.setDate(min.getDate()-days);return date>=min&&date<=now;};
function render(){const search=document.getElementById('history-search').value.toLowerCase();const filter=x=>withinRange(x)&&`${x.task||''} ${x.remark||''} ${x.date}`.toLowerCase().includes(search);const l=laptop.filter(filter),o=offline.filter(filter);document.getElementById('laptop-total').textContent=`${l.length} entries`;document.getElementById('offline-total').textContent=`${o.length} entries`;document.getElementById('laptop-history').innerHTML=rows(l,'task',true);document.getElementById('offline-history').innerHTML=rows(o,'remark');}
function rows(items,field,canDelete=false){const columns=canDelete?6:5;return items.length?items.map(x=>`<tr><td>${escapeHtml(x[field])}</td><td>${formatTime(x.startTime)}</td><td>${formatTime(x.endTime)}</td><td>${secondsToHours(x.durationSeconds)}</td><td>${formatDate(x.date)}</td>${canDelete?`<td><button class="table-action delete-laptop" data-id="${x.id}" aria-label="Delete ${escapeHtml(x.task)}" title="Delete session"><i class="fa-solid fa-trash"></i></button></td>`:''}</tr>`).join(''):`<tr><td colspan="${columns}" class="empty">No entries match these filters.</td></tr>`;}
async function deleteLaptopSession(id){const session=laptop.find(item=>item.id===id);if(!session)return;if(!confirm(`Permanently delete the laptop session “${session.task}”? This cannot be undone.`))return;const button=document.querySelector(`.delete-laptop[data-id="${id}"]`);if(button)button.disabled=true;try{const batch=writeBatch(db);batch.delete(doc(db,'users',uid,'laptopSessions',id));batch.set(doc(db,'users',uid,'dailyStats',session.date),{date:session.date,laptopSeconds:increment(-(session.durationSeconds||0)),totalSeconds:increment(-(session.durationSeconds||0)),sessionCount:increment(-1),updatedAt:serverTimestamp()},{merge:true});await batch.commit();laptop=laptop.filter(item=>item.id!==id);render();notify('Laptop session permanently deleted.');}catch(error){if(button)button.disabled=false;notify(`Could not delete session: ${error.message}`,true)}}
requireUser(async(user)=>{uid=user.uid;[laptop,offline]=await Promise.all([allSessions(uid,'laptopSessions'),allSessions(uid,'offlineSessions')]);render();document.getElementById('history-search').addEventListener('input',render);document.querySelectorAll('#history-filter button').forEach(btn=>btn.onclick=()=>{range=btn.dataset.range;document.querySelectorAll('#history-filter button').forEach(b=>b.classList.toggle('active',b===btn));render();});['history-from','history-to'].forEach(id=>document.getElementById(id).addEventListener('change',render));document.getElementById('laptop-history').onclick=event=>{const button=event.target.closest('.delete-laptop');if(button)deleteLaptopSession(button.dataset.id);};const data=()=>[...laptop.map(x=>({type:'Laptop',title:x.task,...x})),...offline.map(x=>({type:'Offline',title:x.remark,...x}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));document.getElementById('export-csv').onclick=()=>exportCsv(data());document.getElementById('export-excel').onclick=()=>exportExcel(data());document.getElementById('export-pdf').onclick=()=>exportPdf();});
