import { requireUser, dayRange, dailyStats, allSessions, secondsToHours } from './utils.js';
let uid, profile, charts=[];
const color=v=>v>=10?'#006400':v>=9?'#4CAF50':v>=8?'#FF9800':v>=6?'#FDD835':v>=5?'#FF7043':'#E53935';
const group=(items,keyFn)=>Object.entries(items.reduce((o,x)=>{const k=keyFn(x);(o[k]??=[]).push(x);return o;},{})).map(([k,v])=>({key:k,value:v.reduce((s,x)=>s+(x.totalSeconds||0),0)/3600/countDays(k,v)}));
const countDays=(key,values)=> key.startsWith('20')?1:Math.max(1,new Set(values.map(x=>x.date)).size);
function bar(id,labels,values,label){const old=charts.find(x=>x.canvas.id===id);old?.destroy();const chart=new Chart(document.getElementById(id),{type:'bar',data:{labels,datasets:[{label,data:values,backgroundColor:values.map(color),borderRadius:5,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw.toFixed(1)}h average`}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{font:{size:10}}},y:{beginAtZero:true,grid:{color:'#edf0f4'},border:{display:false},ticks:{callback:v=>`${v}h`,font:{size:10}}}}}});charts=charts.filter(x=>x.canvas.id!==id);charts.push(chart);}
function isoWeek(key){const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()+4-(d.getDay()||7));const y=d.getFullYear(),start=new Date(y,0,1);return `${y}-W${String(Math.ceil(((d-start)/86400000+1)/7)).padStart(2,'0')}`;}
function render(stats,sessions,days){const total=stats.reduce((s,x)=>s+(x.totalSeconds||0),0), active=stats.filter(x=>x.totalSeconds).length, avg=total/Math.max(1,days)/3600,longest=Math.max(0,...sessions.map(x=>x.durationSeconds||0));const subjects={};sessions.forEach(x=>{if(x.task)subjects[x.task]=(subjects[x.task]||0)+(x.durationSeconds||0)});const subject=Object.entries(subjects).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';document.getElementById('daily-average').textContent=`${avg.toFixed(1)}h`;document.getElementById('weekly-average').textContent=`${(avg*7).toFixed(1)}h`;document.getElementById('total-study').textContent=secondsToHours(total);document.getElementById('average-session').textContent=sessions.length?secondsToHours(total/sessions.length):'—';document.getElementById('longest-session').textContent=longest?secondsToHours(longest):'—';document.getElementById('most-subject').textContent=subject;const map=Object.fromEntries(stats.map(x=>[x.date,x]));const keys=dayRange(days),values=keys.map(k=>(map[k]?.totalSeconds||0)/3600);const goal=profile.dailyGoal||8;const old=charts.find(x=>x.canvas.id==='daily-chart');old?.destroy();const daily=new Chart(document.getElementById('daily-chart'),{type:'bar',data:{labels:keys.map(k=>new Date(`${k}T12:00:00`).toLocaleDateString([],{month:'short',day:'numeric'})),datasets:[{label:'Study hours',data:values,backgroundColor:values.map(color),borderRadius:5,borderSkipped:false},{type:'line',label:'Daily goal',data:keys.map(()=>goal),borderColor:'#315efb',borderDash:[5,4],borderWidth:1.5,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{afterBody:c=>{const s=map[keys[c[0].dataIndex]]||{};return [`Laptop: ${((s.laptopSeconds||0)/3600).toFixed(1)}h`,`Offline: ${((s.offlineSeconds||0)/3600).toFixed(1)}h`,`Sessions: ${s.sessionCount||0}`,`Goal achieved: ${(s.totalSeconds||0)>=goal*3600?'Yes':'No'}`]}}}},scales:{x:{grid:{display:false},ticks:{maxRotation:0,font:{size:10}}},y:{beginAtZero:true,ticks:{callback:v=>`${v}h`}}}}});charts=charts.filter(x=>x.canvas.id!=='daily-chart');charts.push(daily);const weekly=group(stats,x=>isoWeek(x.date)),monthly=group(stats,x=>x.date.slice(0,7)),quarterly=group(stats,x=>`${x.date.slice(0,4)} Q${Math.floor((Number(x.date.slice(5,7))-1)/3)+1}`),yearly=group(stats,x=>x.date.slice(0,4));bar('weekly-chart',weekly.map(x=>x.key),weekly.map(x=>x.value),'Weekly');bar('monthly-chart',monthly.map(x=>x.key),monthly.map(x=>x.value),'Monthly');bar('quarterly-chart',quarterly.map(x=>x.key),quarterly.map(x=>x.value),'Quarterly');bar('yearly-chart',yearly.map(x=>x.key),yearly.map(x=>x.value),'Yearly');}
async function load(days){const keys=dayRange(days),[stats,sessions]=await Promise.all([dailyStats(uid,keys[0],keys.at(-1)),allSessions(uid,'laptopSessions')]);render(stats.filter(s=>s.date>=keys[0]),sessions.filter(s=>s.date>=keys[0]),days);}
requireUser(async(user,p)=>{uid=user.uid;profile=p;const select=document.getElementById('stats-range');await load(Number(select.value));select.onchange=()=>load(Number(select.value));});
