import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { doc, getDoc, setDoc, updateDoc, increment, serverTimestamp, collection, getDocs, query, where, orderBy } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

export const todayKey = (date = new Date()) => date.toLocaleDateString('en-CA');
export const dateFromKey = key => new Date(`${key}T12:00:00`);
export const secondsToClock = seconds => { seconds = Math.max(0, Math.floor(seconds || 0)); return [seconds / 3600, (seconds % 3600) / 60, seconds % 60].map(n => String(Math.floor(n)).padStart(2, '0')).join(':'); };
export const secondsToHours = seconds => { seconds = Math.max(0, seconds || 0); const h = Math.floor(seconds / 3600), m = Math.round((seconds % 3600) / 60); return h ? `${h}h ${m}m` : `${m}m`; };
export const stampToDate = value => value?.toDate ? value.toDate() : value ? new Date(value) : null;
export const formatTime = value => { const d = stampToDate(value); return d ? d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'; };
export const formatDate = key => dateFromKey(key).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' });
export const escapeHtml = text => String(text || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));

export function notify(message, error = false) { const old = document.querySelector('.toast'); old?.remove(); const node = document.createElement('div'); node.className = `toast${error ? ' error' : ''}`; node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 3200); }

export async function getProfile(uid) { const ref = doc(db, 'users', uid); const snap = await getDoc(ref); if (!snap.exists()) { const profile = { name: auth.currentUser?.displayName || 'Student', email: auth.currentUser?.email || '', dailyGoal: 8, weeklyGoal: 40, monthlyGoal: 160, theme: 'light', createdAt: serverTimestamp() }; await setDoc(ref, profile); return profile; } return snap.data(); }
export async function saveProfile(uid, data) { await setDoc(doc(db, 'users', uid), data, { merge: true }); }
export async function updateDailyStats(uid, date, laptopDelta = 0, offlineDelta = 0, sessionDelta = 0) { const ref = doc(db, 'users', uid, 'dailyStats', date); await setDoc(ref, { date, laptopSeconds: increment(laptopDelta), offlineSeconds: increment(offlineDelta), totalSeconds: increment(laptopDelta + offlineDelta), sessionCount: increment(sessionDelta), updatedAt: serverTimestamp() }, { merge: true }); }
export async function dailyStats(uid, startKey, endKey) { const ref = collection(db, 'users', uid, 'dailyStats'); const q = query(ref, where('date', '>=', startKey), where('date', '<=', endKey), orderBy('date')); return (await getDocs(q)).docs.map(d => ({ id: d.id, ...d.data() })); }
export async function allSessions(uid, type) { const ref = collection(db, 'users', uid, type); const snap = await getDocs(ref); return snap.docs.map(d => ({ id: d.id, ...d.data() })).filter(x => !x.active).sort((a,b) => String(b.date).localeCompare(String(a.date)) || (stampToDate(b.startTime) - stampToDate(a.startTime))); }
export async function sessionsForDay(uid, key) { const [laptop, offline] = await Promise.all([getDocs(query(collection(db,'users',uid,'laptopSessions'), where('date','==',key))), getDocs(query(collection(db,'users',uid,'offlineSessions'),where('date','==',key)))]); return { laptop: laptop.docs.map(d => ({id:d.id,...d.data()})).filter(x=>!x.active), offline: offline.docs.map(d => ({id:d.id,...d.data()})) }; }
export function renderShell(profile = {}) { const page = location.pathname.split('/').pop() || 'dashboard.html'; const links = [['dashboard.html','fa-house','Dashboard'],['history.html','fa-clock-rotate-left','History'],['statistics.html','fa-chart-column','Statistics'],['calendar.html','fa-calendar-days','Calendar'],['settings.html','fa-gear','Settings']]; document.getElementById('app-shell').innerHTML = `<aside class="sidebar"><a class="brand" href="dashboard.html"><span class="brand-mark">S</span>StudyLog <em>Pro</em></a><nav class="nav">${links.map(([href,icon,label])=>`<a class="${page===href?'active':''}" href="${href}"><i class="fa-solid ${icon}"></i>${label}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="user-chip"><span class="avatar">${escapeHtml((profile.name || 'S')[0].toUpperCase())}</span><div><strong>${escapeHtml(profile.name || 'Student')}</strong><small>${escapeHtml(profile.email || '')}</small></div></div></div></aside>`; }
export function requireUser(callback) { return onAuthStateChanged(auth, async user => { if (!user) { location.replace('login.html'); return; } try { const profile = await getProfile(user.uid); document.body.classList.toggle('dark', profile.theme === 'dark'); renderShell(profile); await callback(user, profile); } catch (error) { console.error(error); const code = error?.code || ''; const message = code.includes('permission-denied') ? 'Firestore denied access. Publish the supplied Firestore rules, then refresh.' : code.includes('not-found') || code.includes('failed-precondition') ? 'Cloud Firestore is not ready. Create a Firestore Database in Firebase Console, then refresh.' : `Could not load your account: ${error?.message || 'Firebase connection failed.'}`; notify(message, true); } }); }
export function dayRange(days, end = new Date()) { const out=[]; for(let i=days-1;i>=0;i--){ const d=new Date(end); d.setDate(d.getDate()-i); out.push(todayKey(d)); } return out; }
